Fix installation instructions
Update installation instructions as

	go get -v github.com/anz-bank/sysl/cmd/sysl

results in the following error with Go 1.13 installed:

	github.com/anz-bank/sysl/pkg/sysl
	github.com/anz-bank/sysl/pkg/parser
	# github.com/anz-bank/sysl/pkg/parser
	go/src/github.com/anz-bank/sysl/pkg/parser/grammar.pb.go:23:11: undefined: proto.ProtoPackageIsVersion3
	# github.com/anz-bank/sysl/pkg/sysl
	go/src/github.com/anz-bank/sysl/pkg/sysl/sysl.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3

Pin installation to release v0.4.0 and add GO11MODULE=on env var which
is still required for go 1.13 for installations outside of repos set up
with `go mod`:

	GO111MODULE=on go get github.com/anz-bank/sysl/cmd@v0.4.0